### ISSUE TITLE
Incorrect work with ioctl

### ISSUE THREAD

**Issue by zhum** [kui/revdev#2]
Cannot run samples. Any sample get RangeError like this:

```
$ ruby sample/key_dump /dev/input/mouse0 
/home/serg/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/revdev-0.1.3/lib/revdev/event_device.rb:19:in 'ioctl': integer 2164212998 too big to convert to 'int' (RangeError)
    from /home/serg/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/revdev-0.1.3/lib/revdev/event_device.rb:19:in 'read_ioctl_with'
    from /home/serg/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/revdev-0.1.3/lib/revdev/event_device.rb:33:in 'read_ioctl_as_string_with'
    from /home/serg/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/revdev-0.1.3/lib/revdev/event_device.rb:38:in 'device_name'
    from sample/key_dump:44:in 'main'
    from sample/key_dump:66:in '<main>'
```

**Comment by kui** [comment]
revdev can read events from evdev. But, it cannot read events from `/dev/input/mouse0`.
I think, if you want to read mouse events, you can find any `/dev/input/event*` which is an alternate for `/dev/input/mouse0` to execute `$ ruby sample/device_name /dev/input/event*` or `$ sudo lsinput`.

**Comment by zhum** [comment]
No, the same error:

```
$ ruby sample/device_name /dev/input/event*
/dev/input/event0   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event1   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event10  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event11  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event12  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event13  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event14  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event15  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event16  : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event2   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event3   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event4   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event5   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event6   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event7   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event8   : #<RangeError: integer 2164212998 too big to convert to `int'>
/dev/input/event9   : #<RangeError: integer 2164212998 too big to convert to `int'>
$ sudo lsinput
/dev/input/event0
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x1
   version : 0
   name    : "Power Button"
   phys    : "PNP0C0C/button/input0"
   bits ev : EV_SYN EV_KEY

/dev/input/event1
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x1
   version : 0
   name    : "Power Button"
   phys    : "LNXPWRBN/button/input0"
   bits ev : EV_SYN EV_KEY

/dev/input/event2
   bustype : BUS_USB
   vendor  : 0x46d
   product : 0xc31c
   version : 272
   name    : "Logitech USB Keyboard"
   phys    : "usb-0000:00:1a.0-1.1/input0"
   uniq    : ""
   bits ev : EV_SYN EV_KEY EV_MSC EV_LED EV_REP

/dev/input/event3
   bustype : BUS_USB
   vendor  : 0x46d
   product : 0xc31c
   version : 272
   name    : "Logitech USB Keyboard"
   phys    : "usb-0000:00:1a.0-1.1/input1"
   uniq    : ""
   bits ev : EV_SYN EV_KEY EV_ABS EV_MSC

/dev/input/event4
   bustype : BUS_USB
   vendor  : 0x46d
   product : 0xc52f
   version : 273
   name    : "Logitech USB Receiver"
   phys    : "usb-0000:00:1d.0-1.5/input0"
   uniq    : ""
   bits ev : EV_SYN EV_KEY EV_REL EV_MSC

/dev/input/event5
   bustype : BUS_USB
   vendor  : 0x46d
   product : 0xc52f
   version : 273
   name    : "Logitech USB Receiver"
   phys    : "usb-0000:00:1d.0-1.5/input1"
   uniq    : ""
   bits ev : EV_SYN EV_KEY EV_REL EV_ABS EV_MSC

/dev/input/event6
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Line"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event7
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Front Mic"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event8
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Rear Mic"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event9
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Front Headphone"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event10
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Line Out Side"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event11
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Line Out CLFE"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event12
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Line Out Surround"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event13
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Line Out Front"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event14
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA NVidia HDMI/DP,pcm=7"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event15
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA NVidia HDMI/DP,pcm=3"
   phys    : "ALSA"
   bits ev : EV_SYN EV_SW

/dev/input/event16
   bustype : BUS_BLUETOOTH
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "00:03:89:C5:4B:38"
   bits ev : EV_SYN EV_KEY EV_REL EV_REP

```

I use ubuntu 12.10 x86-64 (may be cause of trouble is 64-bit?)  All input devices are chmoded to allow my user to read and write them.

**Comment by kui** [comment]
umm...
It works fine with my ubuntu 12.04 x86-64. 
I'll test with ubuntu 12.10 x86-64.

**Comment by kui** [comment]
I figured it out.
I think this is a bug of ruby.

ruby `IO#ioctl` with Ubuntu 12.10 has a bug which `IO#ioctl` expect its 2nd args to int.
But, Originally ioctl(2) expect its 2nd args to long.
(see the ioctl definition. e.g. /usr/include/x86_64-linux-gnu/sys/ioctl.h)

Here is a simplest code for this repro:

``` rb
#!/usr/bin/env ruby
# -*- coding:utf-8-unix; mode:ruby; -*-

# an evdev
EVDEV_FILE = "/dev/input/event1"

# an ioctl req to get device name
# see /usr/include/linux/input.h: EVIOCGNAME(255)
IOCTL_REQ = 2164212998

b = ''
open EVDEV_FILE do |evdev|
  evdev.ioctl IOCTL_REQ, b
  # on kernel 3.5.0 (ubuntu 12.10), this ioctl throw a RangeError
end

p b.unpack('Z*')
```

This code works fine on 12.04 amd64 with any ruby version, and do not work on 12.10 amd64 also.

**Comment by kui** [comment]
This is of little relevance to Ubuntu version and Linux kernel version.
To be more precise, this might be [a bug of ruby 1.9.3-p194](http://www.ruby-forum.com/topic/3820494) which used on Ubuntu 12.10 as a defalut ruby runtime, and I confirmed it works fine on ruby 1.9.3-p392.
So, use the latest ruby 1.9.3.

**Comment by zhum** [comment]
Confirm - works fine on  1.9.3-p392! Thank you!
